### ISSUE TITLE
check this

### ISSUE THREAD

**Issue by invisiblecoder99** [AgoraIO/Agora-Web-Electron-Demo#1]
> agora-avc@1.0.0 start /root/agora/Agora-Web-Electron-Demo
> electron .

/root/agora/Agora-Web-Electron-Demo/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! agora-avc@1.0.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the agora-avc@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-21T12_09_16_386Z-debug.log
alpha747:~/agora/Agora-Web-Electron-Demo# ^C
alpha747:~/agora/Agora-Web-Electron-Demo# cd /root/agora/Agora-Web-Electron-Demo/node_modules/electron/dist//root/agora/Agora-Web-Electron-Demo/node_modules/electron/dist/
-bash: cd: /root/agora/Agora-Web-Electron-Demo/node_modules/electron/dist//root/agora/Agora-Web-Electron-Demo/node_modules/electron/dist/: No such file or directory

**Comment by plutoless** [comment]
@quickstreamingmedia  in case you are running on Ubuntu, run following command to install libgconf
apt-get install libgconf-2-4

**Comment by plutoless** [comment]
closed if no more follow up
