### ISSUE TITLE
where is appid in src/pages/meeting/meeting.js

### ISSUE THREAD

**Issue by jhmei** [AgoraIO/Agora-Web-Electron-Demo#4]

**Comment by plutoless** [comment]
![image](https://user-images.githubusercontent.com/471561/56548508-d5610480-65b2-11e9-9701-549d2245e142.png)
you mean this? you will need to register your own appid on agora.io dashboard and put that here.

**Comment by jhmei** [comment]
> ![image](https://user-images.githubusercontent.com/471561/56548508-d5610480-65b2-11e9-9701-549d2245e142.png)
> you mean this? you will need to register your own appid on agora.io dashboard and put that here.

Yes, thanks too much

**Comment by LTonJin** [comment]
@jhmei 
![image](https://user-images.githubusercontent.com/31615159/82864776-e7e90280-9f57-11ea-8144-aa959d68c9e2.png)有报错

**Comment by plutoless** [comment]
@LTonJin 从错误看是开了token，但没有在加入频道时提供，你可以在dashboard建个新的不开token的项目，或者算一下token填到代码里对应join的地方

**Comment by LTonJin** [comment]
> @LTonJin 从错误看是开了token，但没有在加入频道时提供，你可以在dashboard建个新的不开token的项目，或者算一下token填到代码里对应join的地方

对的，谢谢了，一开始新建了个项目是开启了token的，但是没有用就报这个错，后面新建了个没有开启token的用这个appid就可以了
