### ISSUE TITLE
Gtk-Message: 17:12:30.962: Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by jhakamlesh** [AgoraIO/Agora-Web-Electron-Demo#5]
pt-d33@kamlesh:/var/www/html/Electron-With-Web-SDK$ npm start

> agora-avc@1.0.0 start /var/www/html/Electron-With-Web-SDK
> electron .

Gtk-Message: 17:12:30.962: Failed to load module "canberra-gtk-module"

(electron:27640): Pango-ERROR **: 17:12:31.110: Harfbuzz version too old (1.4.2)

**Comment by plutoless** [comment]
sorry this module does not look like ours. i'll close here, feel free to reopen if needed
